services:
  db:
    image: 'mysql:8.0.35-debian'
    environment:
      - MYSQL_ROOT_PASSWORD=root    
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
    volumes:
      - './mysql/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - 'db-data:/var/lib/mysql'

  webserver:
    image: 'my_app_webserver'
    build:
      context: '..'
      dockerfile: 'docker/Dockerfile'
    ports:
      - '9271:80'
    volumes:
      - '../app:/var/www/html' 
      - './php/php.ini:/usr/local/etc/php/php.ini'
      - './apache/apache2.conf:/etc/apache2/apache2.conf'
      - './apache/site.conf:/etc/apache2/sites-available/000-default.conf'
volumes:
  db-data:
    name: 'my_app_db_data'

